version: '3.7'
services:
  App:
    container_name: Aplikacja
    image: test
    build:
      context: ../.
      dockerfile: ./Deployment/Dockerfile
    command: python3 main.py
    #    command: /bin/bash
    ports:
      - "8001:8001"


  postgres:
    container_name: database
    image: library/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=db
    restart: always

  pg_admin:
    container_name: db_admin_panel
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./pgadmin_credentials.env
    restart: always
#    depends_on:
#      - postgres
#    logging:
#      driver: none


# leaving it here for future debugging
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t