json = [
    {
        "id_stacji": "12295",
        "stacja": "Białystok",
        "data_pomiaru": "2021-09-12",
        "godzina_pomiaru": "11",
        "temperatura": "23.7",
        "predkosc_wiatru": "2",
        "kierunek_wiatru": "270",
        "wilgotnosc_wzgledna": "62.1",
        "suma_opadu": "0",
        "cisnienie": "1014.2",
    },
    {
        "id_stacji": "12600",
        "stacja": "Bielsko Biała",
        "data_pomiaru": "2021-09-12",
        "godzina_pomiaru": "11",
        "temperatura": "22.1",
        "predkosc_wiatru": "2",
        "kierunek_wiatru": "330",
        "wilgotnosc_wzgledna": "61.4",
        "suma_opadu": "0",
        "cisnienie": "1017.2",
    },
]
